pipeline {
    agent any
    environment {
        JAVA_HOME = "C:\\Program Files\\Java\\jdk-21.0.10"
        MAVEN_HOME = "C:\\Program Files\\apache-maven-3.9.14-bin\\apache-maven-3.9.14"
        PATH = "${MAVEN_HOME}\\bin;${JAVA_HOME}\\bin;${env.PATH}"
    }
    stages {
        stage('Verify Environment') {
            steps {
                bat 'echo JAVA_HOME=%JAVA_HOME%'
                bat 'java -version'
                bat 'mvn -version'
                bat 'docker --version'
                bat 'docker-compose --version'
            }
        }
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/alexyap14/employee-ms.git'
            }
        }
        stage('Build') {
            steps {
                dir('emloyeems') {
                    bat 'mvn clean package -DskipTests'
                }
            }
        }
        stage('Test') {
            steps {
                dir('emloyeems') {
                    bat 'mvn test'
                }
            }
        }
        stage('Test Reports') {
            steps {
                dir('emloyeems') {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deploy') {
            steps {
                dir('emloyeems') {
                    // Stop and remove previous containers
                    bat 'docker-compose down -v'
                    // Build Docker images and start services (db + web)
                    bat 'docker-compose up -d --build'
                    // Wait for services to be ready
                    sleep 15
                    // Show running containers status
                    bat 'docker-compose ps'
                }
            }
        }
    }
    post {
        success {
            echo 'Build succeeded!!!'
        }
        failure {
            // We only run this if the folder actually exists!
            script {
                if (fileExists('emloyeems/docker-compose.yml')) {
                    dir('emloyeems') {
                        bat 'docker-compose down -v'
                    }
                }
            }
            echo 'Build failed!'
        }
        always {
            echo 'Pipeline finished.'
            // REMOVE or COMMENT OUT deleteDir() for now
            // deleteDir() 
        }
    }
}